/* Generated by Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, clang++ 16.0.0 -fPIC -O3) */

(* src = "circuit.v:1.1-7.10" *)
module simple(a, b, c, y);
  (* src = "circuit.v:2.7-2.8" *)
  input a;
  wire a;
  (* src = "circuit.v:2.9-2.10" *)
  input b;
  wire b;
  (* src = "circuit.v:2.11-2.12" *)
  input c;
  wire c;
  (* src = "circuit.v:3.8-3.9" *)
  output y;
  wire y;
  wire _0_;
  assign _0_ = b & a;
  assign y = _0_ | c;
endmodule
